module.exports = {
    USER_REPOSITORY: 'USER_REPOSITORY',
    ROOM_REPOSITORY: 'ROOM_REPOSITORY',
    SCORE_REPOSITORY: 'SCORE_REPOSITORY',
    MATCH_REPOSITORY: 'MATCH_REPOSITORY',
    SOCKET_SERVER: 'SOCKET_SERVER',
};
