version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost
    ports:
      - 5672:5672

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  pouchdb:
    image: nickdex/pouchdb-server
    ports:
      - 5984:5984
